services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - data:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - srv
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80

      # Redirection from www to without www
      - traefik.http.middlewares.${PROJECT_NAME}_redirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.${PROJECT_NAME}_redirect.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.${PROJECT_NAME}_redirect.redirectregex.permanent=true

      # Middleware security headers
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.frameDeny=true
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.contentTypeNosniff=true
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.stsPreload=true
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.stsSeconds=31536000
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.referrerPolicy=same-origin
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.browserXssFilter=true
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.customRequestHeaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.customRequestHeaders.X-Forwarded-For=$${remoteip}
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.customResponseHeaders.X-Robots-Tag=none
      - traefik.http.middlewares.${PROJECT_NAME}-header.headers.customFrameOptionsValue=SAMEORIGIN

      # Routing apply
      - traefik.http.routers.${PROJECT_NAME}.middlewares=${PROJECT_NAME}_redirect,${PROJECT_NAME}-header
    networks:
      - internal
      - proxy

  srv:
    image: wordpress:php8.4-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/www/html
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mariadb:10.1
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

volumes:
  db:
  data:

networks:
  internal:
    driver: bridge
  proxy:
    external: true
